version: '3.8'

services:
  timescale:
    image: timescale/timescaledb-ha:pg17
    container_name: timescale_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: metrics
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - ts_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d metrics"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  timescaledb_data:

networks:
  ts_network:
    driver: bridge
